#!/usr/bin/env ruby

require_relative "boot"
require "foobara/sh_cli_connector"
require_relative "generate_loan_files_report"

# class FoobaraDemo::LoanOrigination::ReviewAllLoanFiles < Foobara::AgentBackedCommand; end

connector = Foobara::CommandConnectors::ShCliConnector.new
connector.connect(FoobaraDemo::LoanOrigination)
connector.run
