#!/usr/bin/env ruby

require_relative "boot"
require "foobara/sh_cli_connector"

module FoobaraDemo
  module LoanOrigination
    class GenerateLoanFilesReport < Foobara::AgentBackedCommand
      result [
        {
          id: { type: :integer, required: true },
          applicant: { type: :string, required: true },
          state: { type: :string, required: true },
          underwriter_decision: {
            type: LoanFile::UnderwriterDecision,
            description: "Denied reasons omitted if approved"
          }
        }
      ]

      depends_on FindAllLoanFiles
    end
  end
end

connector = Foobara::CommandConnectors::ShCliConnector.new
connector.connect(FoobaraDemo::LoanOrigination)
connector.run
