#!/usr/bin/env ruby

require_relative "boot"
require "foobara/sh_cli_connector"

module FoobaraDemo
  module LoanOrigination
    class ReportRow < Foobara::Model
      attributes do
        id :integer, :required, "The loan file id"
        applicant :string, :required, "The name of the applicant"
        state :string, :required, "The state of the loan file"
        underwriter_decision LoanFile::UnderwriterDecision, "Denied reasons omitted if approved"
      end
    end

    class GenerateLoanFilesReport < Foobara::AgentBackedCommand
      result [ReportRow]
      depends_on FindAllLoanFiles

      llm_model "qwen3:32b"
      # verbose
    end
  end
end

connector = Foobara::CommandConnectors::ShCliConnector.new
connector.connect(FoobaraDemo::LoanOrigination)
connector.run
