#!/usr/bin/env ruby

require_relative "boot"
require "foobara/sh_cli_connector"

module FoobaraDemo
  module LoanOrigination
    class GenerateLoanFilesReport < Foobara::AgentBackedCommand
      result [
        {
          id: :integer,
          applicant: :string,
          state: :string,
          underwriter_decision: LoanFile::UnderwriterDecision
        }
      ]

      depends_on FindAllLoanFiles
    end
  end
end

connector = Foobara::CommandConnectors::ShCliConnector.new
connector.connect(FoobaraDemo::LoanOrigination)
connector.run
