#!/usr/bin/env ruby

require_relative "boot"

module FoobaraDemo
  module LoanOrigination
    class StartUnderwriterReview < Foobara::Command
      inputs do
        loan_file LoanFile, :required
      end

      def execute
        transition_loan_file

        nil
      end

      def transition_loan_file
        loan_file.state_machine.perform_transition!(:start_review)
      end
    end

    class ApproveLoanFile < Foobara::AgentBackedCommand
      depends_on CreateUnderwriterDecision, TransitionLoanFileState

      inputs do
        credit_score_used :integer, :required
        loan_file LoanFile, :required
      end
    end

    class DenyLoanFile < Foobara::AgentBackedCommand
      depends_on CreateUnderwriterDecision, TransitionLoanFileState

      possible_input_error :denied_reasons, :cannot_be_empty

      inputs do
        credit_score_used :integer, :required
        denied_reasons [:denied_reason], :required
        loan_file LoanFile, :required
      end
    end

    class UnderwriterSummary < Foobara::Model
      attributes do
        loan_file_id :integer, :required
        pay_stub_count :integer, :required
        fico_scores [:integer, :integer, :integer], :required
        credit_policy CreditPolicy, :required
      end
    end

    class ReviewLoanFile < Foobara::AgentBackedCommand
      description "Starts the underwriter review then checks requirements in its CreditPolicy " \
                  "and approves or denies accordingly."

      inputs UnderwriterSummary
      result LoanFile::UnderwriterDecision

      depends_on StartUnderwriterReview, DenyLoanFile, ApproveLoanFile
    end

    class ReviewAllLoanFiles < Foobara::AgentBackedCommand
      result [{
        applicant_name: :string,
        decision: LoanFile::UnderwriterDecision
      }]

      depends_on ReviewLoanFile, FindALoanFileThatNeedsReview
    end
  end
end

llm_model = nil

FoobaraDemo::LoanOrigination.foobara_command_classes.each do |command_class|
  next unless command_class < Foobara::AgentBackedCommand

  command_class.verbose
  command_class.llm_model(llm_model) if llm_model
end

outcome = FoobaraDemo::LoanOrigination::ReviewAllLoanFiles.run

if outcome.success?
  outcome.result.each do |name_and_decision|
    name, decision = name_and_decision.values_at(:applicant_name, :decision)

    if decision.denied?
      puts "Denied: #{name}"
      puts "Reason: #{decision.denied_reasons.join(", ")}"
    else
      puts "Approve: #{name}"
    end
    puts
  end
else
  puts outcome.errors_hash
end
